# Site Settings
title: Jekyll Cart
description: A Jekyll Based Shopping Cart Built with simpleCart(js)
url:

# Jekyll Configuration
encoding: UTF-8
permalink: /:title/
paginate: 5
paginate_path: "/blog/page/:num/"

# Markdown Processing
markdown: kramdown
kramdown:
  input: GFM

# Sass/SCSS settings
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Custom Collections
collections:
  products:
    output: true

# Collection Defaults
defaults:
- scope:
    type: posts
  values:
    layout: post
- scope:
    type: pages
  values:
    layout: page
- scope:
    type: products
  values:
    layout: product

# Frontmatter Defaults
sidebar_options:
  - sidebar
  - no-sidebar

# File Handling
# include: [_pages]
exclude: [lib, config.rb, .sass-cache, Capfile, config, log, Rakefile, Rakefile.rb, tmp, Gemfile, Gemfile.lock, README.md, LICENSE.md, node_modules, gulpfile.js, package.json]

# Plugins
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-paginate

# Archives
jekyll-archives:
  enabled:
    - categories
    - tags
  permalinks:
    categories: '/category/:name/'
    tags: '/tag/:name/'

# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development
